name: Amet Finance Web Production

on:
  push:
    branches: [ "ui-changes-v2" ]
  pull_request:
    branches: [ "ui-changes-v2" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to Server and Restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_MAIN }}
        username: ${{ secrets.USERNAME_MAIN }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/web-v2
          git pull && npm i && npm run build && pm2 restart 4
