name: Amet Finance Web Production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to Server and Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_MAIN }}
          username: ${{ secrets.USERNAME_MAIN }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/web
            git pull && npm i && npm run build && sudo systemctl restart myapp.service
